"""empty message

Revision ID: 3b19e6a538fd
Revises: None
Create Date: 2018-03-17 03:07:40.026312

"""

# revision identifiers, used by Alembic.
revision = '3b19e6a538fd'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Blogs')
    op.drop_table('Postbirth')
    op.add_column('Users', sa.Column('designation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'designation')
    op.create_table('Postbirth',
    sa.Column('article_id', sa.INTEGER(), server_default=sa.text('nextval(\'"Postbirth_article_id_seq"\'::regclass)'), nullable=False),
    sa.Column('month_no', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('article', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dos', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('donts', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('diet', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('article_id', name='Postbirth_pkey')
    )
    op.create_table('Blogs',
    sa.Column('blog_id', sa.INTEGER(), server_default=sa.text('nextval(\'"Blogs_blog_id_seq"\'::regclass)'), nullable=False),
    sa.Column('author_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('article', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('author_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('time_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('keywords', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('blog_id', name='Blogs_pkey')
    )
    # ### end Alembic commands ###
